refactor Deployment Pipeline and integrate with Test Automation Pipeline

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -1,4 +1,4 @@
-name: Validate Deployment
+name: Deploy-Test-Cleanup Pipeline
 on:
   push:
     branches:
@@ -9,28 +9,37 @@ on:
   schedule:
     - cron: "0 10,22 * * *" # Runs at 10:00 AM and 10:00 PM GMT
 
+env:
+  GPT_CAPACITY: 250
+  TEXT_EMBEDDING_CAPACITY: 200
+
 jobs:
   deploy:
-    runs-on: ubuntu-latest # Use a Windows runner for PowerShell scripts
+    runs-on: ubuntu-latest
+    outputs:
+      RESOURCE_GROUP_NAME: ${{ steps.get_webapp_url.outputs.RESOURCE_GROUP_NAME }}
+      KUBERNETES_RESOURCE_GROUP_NAME: ${{ steps.get_webapp_url.outputs.KUBERNETES_RESOURCE_GROUP_NAME }}
+      WEBAPP_URL: ${{ steps.get_webapp_url.outputs.WEBAPP_URL }}
+      OPENAI_RESOURCE_NAME: ${{ steps.get_webapp_url.outputs.OPENAI_RESOURCE_NAME }}
+      DOCUMENT_INTELLIGENCE_RESOURCE_NAME: ${{ steps.get_webapp_url.outputs.DOCUMENT_INTELLIGENCE_RESOURCE_NAME }}
+      VALID_REGION: ${{ steps.get_webapp_url.outputs.VALID_REGION }}
 
     steps:
       - name: Checkout Code
         uses: actions/checkout@v4 # Checks out your repository
-        # Install Azure CLI
+
       - name: Install Azure CLI
         shell: bash
         run: |
           curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
           az --version  # Verify installation
 
-      # Install kubectl (Windows method)
-      - name: Install kubectl
+      - name: Install Kubernetes CLI (kubectl)
         shell: bash
         run: |
           az aks install-cli
           az extension add --name aks-preview
 
-        # Install Helm (Windows method)
       - name: Install Helm
         shell: bash
         run: |
@@ -40,21 +49,11 @@ jobs:
           sudo apt-get update
           sudo apt-get install helm
 
-      # - name: Set Docker environment variables
-      #   run: echo "DOCKER_BUILDKIT=0" >> $GITHUB_ENV
-
-        # Set up Docker
       - name: Set up Docker
         uses: docker/setup-buildx-action@v3
         with:
           driver: docker
 
-      - name: Setup PowerShell
-        shell: pwsh
-        run: |
-          $PSVersionTable.PSVersion
-
-      # Run Quota Check Script
       - name: Run Quota Check
         id: quota-check
         shell: pwsh
@@ -85,11 +84,10 @@ jobs:
           AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
           AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
           AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
-          GPT_MIN_CAPACITY: "10"
-          TEXT_EMBEDDING_MIN_CAPACITY: "10"
+          GPT_MIN_CAPACITY: ${{ env.GPT_CAPACITY }}
+          TEXT_EMBEDDING_MIN_CAPACITY: ${{ env.TEXT_EMBEDDING_CAPACITY }}
           AZURE_REGIONS: "${{ vars.AZURE_REGIONS }}"
 
-      # Send Notification on Quota Failure
       - name: Send Notification on Quota Failure
         if: env.QUOTA_FAILED == 'true'
         shell: pwsh
@@ -99,7 +97,7 @@ jobs:
           # Construct the email body
           $EMAIL_BODY = @"
           {
-            "body": "<p>Dear Team,</p><p>The quota check has failed, and the pipeline cannot proceed.</p><p><strong>Build URL:</strong> $RUN_URL</p><p>Please take necessary action.</p><p>Best regards,<br>Your Automation Team</p>"
+            "body": "<p>Dear Team,</p><p>The quota check has failed, and the pipeline cannot proceed.</p><p><strong>Build URL:</strong> <a href='$RUN_URL'>$RUN_URL</a></p><p>Please take necessary action.</p><p>Best regards,<br>Your Automation Team</p>"
           }
           "@
 
@@ -141,94 +139,184 @@ jobs:
           yes
           "@
           $input | pwsh ./resourcedeployment.ps1
-          echo "Resource Group Name is ${{ env.rg_name }}"
-          echo "Kubernetes resource group are ${{ env.krg_name }}"
+          Write-Host "Resource Group Name is ${{ env.rg_name }}"
+          Write-Host "Kubernetes resource group are ${{ env.krg_name }}"
         env:
           AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
           AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
           AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
           AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
-          
-      - name: Cleanup Resource Group
-        if: always() # Ensures this step runs even if the deployment fails
+
+      - name: Extract Web App URL and Increase TPM
+        id: get_webapp_url
+        shell: bash
+        run: |
+          # Save the resource group name and Kubernetes resource group name to GITHUB_OUTPUT
+          echo "RESOURCE_GROUP_NAME=${{ env.rg_name }}" >> $GITHUB_OUTPUT
+          echo "KUBERNETES_RESOURCE_GROUP_NAME=${{ env.krg_name }}" >> $GITHUB_OUTPUT
+          echo "VALID_REGION=${{ env.VALID_REGION }}" >> $GITHUB_OUTPUT
+
+          if az account show &> /dev/null; then
+            echo "Azure CLI is authenticated."
+          else
+            echo "Azure CLI is not authenticated. Logging in..."
+            az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
+          fi
+          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+
+          # Get the Web App URL and save it to GITHUB_OUTPUT
+          echo "Retrieving Web App URL..."
+          public_ip_name=$(az network public-ip list --resource-group ${{ env.krg_name }} --query "[?contains(name, 'kubernetes-')].name" -o tsv)
+          fqdn=$(az network public-ip show --resource-group ${{ env.krg_name }} --name $public_ip_name --query "dnsSettings.fqdn" -o tsv)
+          if [ -n "$fqdn" ]; then
+            echo "WEBAPP_URL=https://$fqdn" >> $GITHUB_OUTPUT
+            echo "Web App URL is https://$fqdn"
+          else
+            echo "Failed to retrieve Web App URL."
+            exit 1
+          fi
+
+          # Get Azure OpenAI resource name
+          openai_resource_name=$(az cognitiveservices account list --resource-group ${{ env.rg_name }} --query "[?kind=='OpenAI'].name | [0]" -o tsv)
+          if [ -z "$openai_resource_name" ]; then
+            echo "No Azure OpenAI resource found in the resource group."
+            exit 1
+          fi
+          echo "OpenAI resource name is $openai_resource_name"
+          echo "OPENAI_RESOURCE_NAME=$openai_resource_name" >> $GITHUB_OUTPUT
+
+          # Get Azure Document Intelligence resource name
+          document_intelligence_resource_name=$(az cognitiveservices account list --resource-group ${{ env.rg_name }} --query "[?kind=='FormRecognizer'].name | [0]" -o tsv)
+          if [ -z "$document_intelligence_resource_name" ]; then
+            echo "No Azure Document Intelligence resource found in the resource group."
+          else
+            echo "Document Intelligence resource name is $document_intelligence_resource_name"
+            echo "DOCUMENT_INTELLIGENCE_RESOURCE_NAME=$document_intelligence_resource_name" >> $GITHUB_OUTPUT
+          fi
+
+          # Increase the TPM for the Azure OpenAI models
+          echo "Increasing TPM for Azure OpenAI models..."
+          openai_gpt_deployment_url="/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ env.rg_name }}/providers/Microsoft.CognitiveServices/accounts/$openai_resource_name/deployments/gpt-4o-mini?api-version=2023-05-01"
+          az rest -m put -u "$openai_gpt_deployment_url" -b "{'sku':{'name':'Standard','capacity':${{ env.GPT_CAPACITY }}},'properties': {'model': {'format': 'OpenAI','name': 'gpt-4o-mini','version': '2024-07-18'}}}"
+          if [ $? -ne 0 ]; then
+            echo "Failed to increase TPM for GPT deployment."
+            exit 1
+          else
+            echo "Successfully increased TPM for GPT deployment."
+          fi
+          openai_embedding_deployment_url="/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ env.rg_name }}/providers/Microsoft.CognitiveServices/accounts/$openai_resource_name/deployments/text-embedding-large?api-version=2023-05-01"
+          az rest -m put -u "$openai_embedding_deployment_url" -b "{'sku':{'name':'Standard','capacity': ${{ env.TEXT_EMBEDDING_CAPACITY }}},'properties': {'model': {'format': 'OpenAI','name': 'text-embedding-3-large','version': '1'}}}"
+          if [ $? -ne 0 ]; then
+            echo "Failed to increase TPM for Text Embedding deployment."
+            exit 1
+          else
+            echo "Successfully increased TPM for Text Embedding deployment."
+          fi
+
+      - name: Run Post Deployment Script
         shell: pwsh
+        run: |
+          cd Deployment
+          .\uploadfiles.ps1 -EndpointUrl "${{ steps.get_webapp_url.outputs.WEBAPP_URL }}"
+          if ($LASTEXITCODE -ne 0) {
+            Write-Host "❌ Post deployment script failed."
+            exit 1
+          } else {
+            Write-Host "✅ Post deployment script completed successfully."
+          }
+
+      - name: Logout from Azure
+        if: always()
+        shell: bash
+        run: |
+          if az account show &> /dev/null; then
+            echo "Logging out from Azure..."
+            az logout
+            echo "Logged out from Azure successfully."
+          else
+            echo "Azure CLI is not authenticated. Skipping logout."
+          fi
+
+
+  e2e-test:
+    needs: deploy
+    uses: ./.github/workflows/test-automation.yml
+    with:
+      DKM_URL: ${{ needs.deploy.outputs.WEBAPP_URL }}
+    secrets: inherit
+
+
+  cleanup-deployment:
+    if: always()
+    needs: [deploy, e2e-test]
+    runs-on: ubuntu-latest
+    env:
+      RESOURCE_GROUP_NAME: ${{ needs.deploy.outputs.RESOURCE_GROUP_NAME }}
+      KUBERNETES_RESOURCE_GROUP_NAME: ${{ needs.deploy.outputs.KUBERNETES_RESOURCE_GROUP_NAME }}
+      OPENAI_RESOURCE_NAME: ${{ needs.deploy.outputs.OPENAI_RESOURCE_NAME }}
+      DOCUMENT_INTELLIGENCE_RESOURCE_NAME: ${{ needs.deploy.outputs.DOCUMENT_INTELLIGENCE_RESOURCE_NAME }}
+      VALID_REGION: ${{ needs.deploy.outputs.VALID_REGION }}
+
+    steps:
+      - name: Install Azure CLI
+        shell: bash
+        run: |
+          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
+          az --version  # Verify installation
+          
+      - name: Login to Azure
+        shell: bash
         run: |
           az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
-          az group delete --name ${{ env.rg_name }} --yes --no-wait
-          az group delete --name ${{ env.krg_name }} --yes --no-wait
-        env:
-          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
-          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
-          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
-          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
+          az account set --subscription "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
+
+      - name: Delete Resource Groups
+        if: always()
+        shell: bash
+        run: |
+          az group delete --name ${{ env.RESOURCE_GROUP_NAME }} --yes --no-wait
+          az group delete --name ${{ env.KUBERNETES_RESOURCE_GROUP_NAME }} --yes --no-wait
 
       - name: Wait for Resource Deletion to Complete
-        shell: pwsh
+        shell: bash
         run: |
-          $retries = 0
-          $maxRetries = 3
-          $sleepIntervals = @(700, 200, 200)
+          echo "Waiting for Azure OpenaAI and Document Intelligence resources to be deleted..."
+          sleep 60 
+          retries=0
+          max_retries=3
+          sleep_duration=60
+          while [ $retries -lt $max_retries ]; do
+            aoai_exists=$(az resource list --resource-group ${{ env.RESOURCE_GROUP_NAME }} --name ${{ env.OPENAI_RESOURCE_NAME }} --query "[0].name" -o tsv)
+            di_exists=$(az resource list --resource-group ${{ env.RESOURCE_GROUP_NAME }} --name ${{ env.DOCUMENT_INTELLIGENCE_RESOURCE_NAME }} --query "[0].name" -o tsv)
 
-          while ($retries -lt $maxRetries) {
-            $rgStatus = az group exists --name ${{ env.rg_name }}
-            $krgStatus = az group exists --name ${{ env.krg_name }}
-            
-
-            # if (-not $rgStatus -and -not $krgStatus) {
-            #   Write-Host "Both resource groups deleted successfully."
-            #   break
-            # }
-            if ($rgStatus -eq "false" -and $krgStatus -eq "false") {
-              Write-Host "Both resource groups deleted successfully."
+            if [ -z "$aoai_exists" ] && [ -z "$di_exists" ]; then
+              echo "Resources deleted successfully."
               break
-            }
-
-            $retries++
-            if ($retries -eq $maxRetries) {
-              Write-Host "Resource groups deletion not confirmed after $maxRetries attempts. Exiting."
-              exit 1
-            }
-
-            Write-Host "Resource groups still exist. Retrying in $($sleepIntervals[$retries - 1]) seconds..."
-            Start-Sleep -Seconds $sleepIntervals[$retries - 1]
-          }
+            else
+              echo "Resources still exist, retrying in $((sleep_duration * (retries + 1))) seconds..."
+              sleep $((sleep_duration * (retries + 1)))
+              retries=$((retries + 1))
+            fi
+          done
 
       - name: Purging the Resources
         if: success()
-        shell: pwsh
+        shell: bash
         run: |
-          # Set variables using GitHub Actions environment values
-          $solutionPrefix = "${{ env.SOLUTION_PREFIX }}"
-          $subscriptionId = "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
-          $resourceGroupName = "${{ env.rg_name }}"
+          echo "Purging the Azure OpenAI and Document Intelligence resources..."
+          if [ -z "${{ env.OPENAI_RESOURCE_NAME }}" ]; then
+            echo "No Azure OpenAI resource to purge."
+          else
+            echo "Purging Azure OpenAI resource..."
+            az cognitiveservices account purge --name ${{ env.OPENAI_RESOURCE_NAME }} --resource-group ${{ env.RESOURCE_GROUP_NAME }} --location ${{ env.VALID_REGION }}
+          fi
 
-          $openai_name = "openaiservice-$solutionPrefix"
-          $cognitiveservice_name = "cognitiveservice-$solutionPrefix"
-
-          # Debug: Print resource names
-          Write-Host "Purging OpenAI resource: $openai_name"
-          Write-Host "Purging CognitiveService Account: $cognitiveservice_name"
-
-          # Construct resource IDs
-          $openaiResourceId = "/subscriptions/$subscriptionId/providers/Microsoft.CognitiveServices/locations/${{ env.VALID_REGION }}/resourceGroups/$resourceGroupName/deletedAccounts/$openai_name"
-          $cognitiveResourceId = "/subscriptions/$subscriptionId/providers/Microsoft.CognitiveServices/locations/${{ env.VALID_REGION }}/resourceGroups/$resourceGroupName/deletedAccounts/$cognitiveservice_name"
-
-          # Debug: Print constructed resource IDs
-          Write-Host "Command to purge OpenAI resource: az resource delete --ids `"$openaiResourceId`" --verbose"
-          Write-Host "Command to purge CognitiveService Account: az resource delete --ids `"$cognitiveResourceId`" --verbose"
-            # Purge OpenAI Resource
-              az resource delete --ids $openaiResourceId --verbose
-              if (-not $?) {
-                  Write-Host "Failed to purge OpenAI resource: $openaiResourceId"
-              }
-
-              # Purge CognitiveService Account
-
-
-              az resource delete --ids $cognitiveResourceId --verbose
-              if (-not $?) {
-                  Write-Host "Failed to purge CognitiveService Account."
-              }
+          if [ -z "${{ env.DOCUMENT_INTELLIGENCE_RESOURCE_NAME }}" ]; then
+            echo "No Azure Document Intelligence resource to purge."
+          else
+            echo "Purging Azure Document Intelligence resources..."
+            az cognitiveservices account purge --name ${{ env.DOCUMENT_INTELLIGENCE_RESOURCE_NAME }} --resource-group ${{ env.RESOURCE_GROUP_NAME }} --location ${{ env.VALID_REGION }}
+          fi
 
       - name: Send Notification on Failure
         if: failure()
@@ -252,3 +340,15 @@ jobs:
           } catch {
               Write-Output "Failed to send notification."
           }
+
+      - name: Logout from Azure
+        if: always()
+        shell: bash
+        run: |
+          if az account show &> /dev/null; then
+            echo "Logging out from Azure..."
+            az logout
+            echo "Logged out from Azure successfully."
+          else
+            echo "Azure CLI is not authenticated. Skipping logout."
+          fi
