Update tests.yml

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -34,12 +34,12 @@ jobs:
       - name: Restore and run tests for Backend API with coverage
         working-directory: ./App/backend-api
         run: |
-               if [ -f "Microsoft.GS.DPS.sln" ]; then
-                  dotnet restore Microsoft.GS.DPS.sln || echo "Warning: Some dependencies are missing. Proceeding."
-                  dotnet test Microsoft.GS.DPS.Host/BackendApi.Tests/BackendApi.Tests.csproj --collect:"XPlat Code Coverage" --logger "trx;LogFileName=TestResults.trx" --results-directory TestResults || echo "Warning: Some tests may have failed."
-                else
-                echo "No solution file found in Backend API. Skipping tests."
-                fi
+          if [ -f "Microsoft.GS.DPS.sln" ]; then
+             dotnet restore Microsoft.GS.DPS.sln || echo "Warning: Some dependencies are missing. Proceeding."
+             dotnet test Microsoft.GS.DPS.Host/BackendApi.Tests/BackendApi.Tests.csproj --collect:"XPlat Code Coverage" --logger "trx;LogFileName=TestResults.trx" --results-directory TestResults || echo "Warning: Some tests may have failed."
+          else
+             echo "No solution file found in Backend API. Skipping tests."
+          fi
       - name: List test result files
         run: ls -R ./App/backend-api/TestResults || echo "TestResults directory not found."
       - name: Verify Coverage Report
