Update tests.yml6

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -37,7 +37,7 @@ jobs:
           if [ -f "Microsoft.GS.DPS.sln" ]; then
             dotnet restore Microsoft.GS.DPS.sln || echo "Warning: Some dependencies are missing. Proceeding."
             if dotnet test Microsoft.GS.DPS.sln --list-tests > /dev/null 2>&1; then
-              dotnet test Microsoft.GS.DPS.sln --collect:"XPlat Code Coverage" --logger trx --results-directory TestResults || echo "Warning: Some tests may have failed."
+              dotnet test Microsoft.GS.DPS.Host/BackendApi.Tests/BackendApi.Tests.csproj --collect:"XPlat Code Coverage" --settings coverlet.runsettings --logger trx --results-directory TestResults || echo "Warning: Some tests may have failed."
             else
               echo "No test cases found in Backend API. Skipping tests."
             fi
@@ -46,6 +46,14 @@ jobs:
           fi
       - name: List test result files
         run: ls -R ./App/backend-api/TestResults || echo "TestResults directory not found."
+      - name: Verify Coverage Report
+        run: |
+          if [ -d "./App/backend-api/TestResults/CoverageReport" ]; then
+              echo "Coverage report exists."
+          else
+            echo "Coverage report not generated."
+          fi
+
 
 
       - name: Publish coverage results for Backend API
