Update tests.yml1

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -31,13 +31,14 @@ jobs:
           if [ -f "Microsoft.GS.DPS.sln" ]; then
             dotnet restore Microsoft.GS.DPS.sln || echo "Warning: Some dependencies are missing. Proceeding."
             if dotnet test Microsoft.GS.DPS.sln --list-tests > /dev/null 2>&1; then
-             dotnet test Microsoft.GS.DPS.sln --no-build --verbosity normal --collect:"Code Coverage" || echo "Warning: Some tests may have failed."
+              dotnet test Microsoft.GS.DPS.sln --no-build --verbosity normal --collect:"XPlat Code Coverage" || echo "Warning: Some tests may have failed."
             else
               echo "No test cases found in Backend API. Skipping tests."
             fi
           else
             echo "No solution file found in Backend API. Skipping tests."
           fi
+
       - name: Install ReportGenerator
         run: dotnet tool install --global dotnet-reportgenerator-globaltool
 
@@ -45,7 +46,7 @@ jobs:
         run: |
           REPORT_DIR="./coverage-report"
           mkdir -p $REPORT_DIR
-          reportgenerator -reports:**/TestResults/**/*.coverage -targetdir:$REPORT_DIR -reporttypes:TextSummary
+          reportgenerator -reports:**/TestResults/**/*.cobertura.xml -targetdir:$REPORT_DIR -reporttypes:TextSummary
 
       - name: Display Coverage Summary
         run: cat ./coverage-report/Summary.txt
@@ -68,13 +69,25 @@ jobs:
           if [ -f "KernelMemory.sln" ]; then
             dotnet restore KernelMemory.sln || echo "Warning: Some dependencies are missing. Proceeding."
             if dotnet test KernelMemory.sln --list-tests > /dev/null 2>&1; then
-             dotnet test KernelMemory.sln --no-build --verbosity normal --collect:"Code Coverage" || echo "Warning: Some tests may have failed."
+              dotnet test KernelMemory.sln --no-build --verbosity normal --collect:"XPlat Code Coverage" || echo "Warning: Some tests may have failed."
             else
               echo "No test cases found in Kernel Memory. Skipping tests."
             fi
           else
             echo "No solution file found in Kernel Memory. Skipping tests."
           fi
+
+      - name: Install ReportGenerator
+        run: dotnet tool install --global dotnet-reportgenerator-globaltool
+
+      - name: Generate Coverage Report
+        run: |
+          REPORT_DIR="./coverage-report"
+          mkdir -p $REPORT_DIR
+          reportgenerator -reports:**/TestResults/**/*.cobertura.xml -targetdir:$REPORT_DIR -reporttypes:TextSummary
+
+      - name: Display Coverage Summary
+        run: cat ./coverage-report/Summary.txt
 
   frontend_tests:
     runs-on: ubuntu-latest
