Update tests.yml4

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -31,15 +31,16 @@ jobs:
           if [ -f "Microsoft.GS.DPS.sln" ]; then
             dotnet restore Microsoft.GS.DPS.sln || echo "Warning: Some dependencies are missing. Proceeding."
             if dotnet test Microsoft.GS.DPS.sln --list-tests > /dev/null 2>&1; then
-              dotnet test Microsoft.GS.DPS.Host/BackendApi.Tests/BackendApi.Tests.csproj --collect:"XPlat Code Coverage" --logger trx --results-directory TestResults || echo "Some tests may have failed."
+              dotnet test Microsoft.GS.DPS.sln --collect:"XPlat Code Coverage" --logger trx --results-directory TestResults || echo "Warning: Some tests may have failed."
             else
               echo "No test cases found in Backend API. Skipping tests."
             fi
           else
             echo "No solution file found in Backend API. Skipping tests."
           fi
-        env:
-          DOTNET_ROOT: /usr/share/dotnet
+      - name: List test result files
+        run: ls -R ./App/backend-api/TestResults || echo "TestResults directory not found."
+
 
       - name: Publish coverage results for Backend API
         uses: actions/upload-artifact@v3
